/**
 * Comprehensive lookalike & phonetic confuser matrices for Hiragana & Katakana.
 */

export const HIRAGANA_CONFUSERS: Record<string, string[]> = {
  a: ['o', 'me', 'wa', 'e'],
  i: ['ri', 'ko', 'ni', 'u'],
  u: ['tsu', 'ra', 'fu', 'i'],
  e: ['n', 'i', 'te', 'a'],
  o: ['a', 'ka', 'yo', 'u'],
  ka: ['ki', 'ku', 'ke', 'ko', 'wa', 'o', 'ga'],
  ki: ['ka', 'ku', 'ke', 'ko', 'sa', 'chi', 'gi'],
  ku: ['ka', 'ki', 'ke', 'ko', 'he', 'shi', 'gu'],
  ke: ['ka', 'ki', 'ku', 'ko', 'ha', 'ni', 'ge'],
  ko: ['ka', 'ki', 'ku', 'ke', 'ni', 'i', 'go'],
  sa: ['shi', 'su', 'se', 'so', 'ki', 'chi', 'za'],
  shi: ['sa', 'su', 'se', 'so', 'tsu', 'ku', 'ji'],
  su: ['sa', 'shi', 'se', 'so', 'mu', 'nu', 'zu'],
  se: ['sa', 'shi', 'su', 'so', 'ya', 'ze'],
  so: ['sa', 'shi', 'su', 'se', 'ro', 'ru', 'zo'],
  ta: ['chi', 'tsu', 'te', 'to', 'na', 'da'],
  chi: ['ta', 'tsu', 'te', 'to', 'sa', 'ra', 'ji'],
  tsu: ['ta', 'chi', 'te', 'to', 'u', 'shi'],
  te: ['ta', 'chi', 'tsu', 'to', 'so', 'de'],
  to: ['ta', 'chi', 'tsu', 'te', 'do'],
  na: ['ni', 'nu', 'ne', 'no', 'ta'],
  ni: ['na', 'nu', 'ne', 'no', 'ko', 'ke', 'i'],
  nu: ['na', 'ni', 'ne', 'no', 'me'],
  ne: ['na', 'ni', 'nu', 'no', 're', 'wa'],
  no: ['na', 'ni', 'nu', 'ne', 'me'],
  ha: ['hi', 'fu', 'he', 'ho', 'ma', 'ke', 'ba', 'pa'],
  hi: ['ha', 'fu', 'he', 'ho', 'bi', 'pi'],
  fu: ['ha', 'hi', 'he', 'ho', 'u', 'bu', 'pu'],
  he: ['ha', 'hi', 'fu', 'ho', 'ku', 'be', 'pe'],
  ho: ['ha', 'hi', 'fu', 'he', 'ma', 'bo', 'po'],
  ma: ['mi', 'mu', 'me', 'mo', 'ho', 'ha'],
  mi: ['ma', 'mu', 'me', 'mo', 'ki'],
  mu: ['ma', 'mi', 'me', 'mo', 'su'],
  me: ['ma', 'mi', 'mu', 'mo', 'nu', 'a', 'no'],
  mo: ['ma', 'mi', 'mu', 'me', 'shi'],
  ya: ['yu', 'yo', 'se', 'ka'],
  yu: ['ya', 'yo', 'u'],
  yo: ['ya', 'yu', 'ma', 'o'],
  ra: ['ri', 'ru', 're', 'ro', 'chi', 'u'],
  ri: ['ra', 'ru', 're', 'ro', 'i'],
  ru: ['ra', 'ri', 're', 'ro', 'so'],
  re: ['ra', 'ri', 'ru', 'ro', 'ne', 'wa'],
  ro: ['ra', 'ri', 'ru', 're', 'ru'],
  wa: ['wo', 'n', 're', 'ne', 'ka'],
  wo: ['wa', 'n', 'to', 'e', 'o'],
  n: ['wa', 'wo', 'e', 'so']
};

export const KATAKANA_CONFUSERS: Record<string, string[]> = {
  a: ['u', 'fu', 'ra', 'ka'],
  i: ['ku', 'to', 'ha', 'te'],
  u: ['a', 'fu', 'ra', 'wa'],
  e: ['ko', 'yo', 'ni', 'i'],
  o: ['ko', 'to', 'ho', 'a'],
  ka: ['ku', 'ke', 'ko', 'ga', 'chikara'],
  ki: ['sa', 'shi', 'te', 'gi'],
  ku: ['wa', 'ta', 'fu', 'ke', 'gu'],
  ke: ['ku', 'ta', 'ni', 'ge'],
  ko: ['e', 'ro', 'go', 'yo'],
  sa: ['chi', 'se', 'so', 'za'],
  shi: ['tsu', 'so', 'n', 'ji'],
  su: ['nu', 'fu', 'wo', 'zu'],
  se: ['sa', 'hi', 'ze'],
  so: ['n', 'shi', 'tsu', 'zo'],
  ta: ['ku', 'ke', 'da'],
  chi: ['te', 'sa', 'ji'],
  tsu: ['shi', 'so', 'n'],
  te: ['chi', 'de'],
  to: ['i', 'do'],
  na: ['me', 'ya'],
  ni: ['ko', 'mi'],
  nu: ['su', 'fu'],
  ne: ['ho', 'ha'],
  no: ['so', 'me'],
  ha: ['ba', 'pa', 'he'],
  hi: ['bi', 'pi', 'se'],
  fu: ['u', 'a', 'ra', 'bu', 'pu'],
  he: ['ha', 'be', 'pe'],
  ho: ['ne', 'bo', 'po'],
  ma: ['mu', 'mo', 'a'],
  mi: ['ni', 'san'],
  mu: ['ma', 'ra'],
  me: ['nu', 'no', 'na'],
  mo: ['ma', 'te'],
  ya: ['se', 'na'],
  yu: ['ko', 'yo'],
  yo: ['ko', 'e'],
  ra: ['fu', 'u', 'ro'],
  ri: ['i', 'ru'],
  ru: ['re', 'ro'],
  re: ['ru', 'ro'],
  ro: ['ko', 'ru'],
  wa: ['ku', 'u', 'wo'],
  wo: ['wa', 'su'],
  n: ['so', 'shi', 'tsu']
};

export const TWIN_CONFUSER_PAIRS: [string, string][] = [
  // Hiragana twins
  ['a', 'o'],
  ['nu', 'me'],
  ['ne', 're'],
  ['wa', 're'],
  ['wa', 'ne'],
  ['sa', 'ki'],
  ['chi', 'ra'],
  ['tsu', 'shi'],
  ['ha', 'ho'],
  ['ma', 'mo'],
  ['ru', 'ro'],
  ['i', 'ri'],
  ['ta', 'na'],
  // Katakana twins
  ['kata_shi', 'kata_tsu'],
  ['kata_so', 'kata_n'],
  ['kata_ku', 'kata_wa'],
  ['kata_nu', 'kata_su'],
  ['kata_chi', 'kata_te'],
  ['kata_a', 'kata_fu'],
  ['kata_u', 'kata_wa'],
  ['kata_ko', 'kata_yo'],
  ['kata_me', 'kata_nu']
];
